### ISSUE TITLE
   大神   请问七牛的推流地址怎么设置？

### ISSUE THREAD

**Issue by backups123** [jjdxmashl/jjdxm_pililive#1]
大神          try {
                            UIUtils.showToastCenterShort("直播开始！");
                            mJSONObject = new JSONObject(liveId);
                            StreamingProfile.Stream stream = new StreamingProfile.Stream(mJSONObject);
                            mProfile.setStream(stream);  // You can invoke this before startStreaming, but not in initialization phase.
                            mCameraStreamingManager.setStreamingProfile(mProfile);
                            //这里没有打开只是简单测试功能没有去推流的
                            mCameraStreamingManager.startStreaming();
                            isStarted = true;
                        } catch (JSONException e) {
                            e.printStackTrace();
                            UIUtils.showToastCenterShort("推流地址解析失败！");
                        }

在这里如何设置？？？

**Comment by jjdxmashl** [comment]
@backups123 不好意思比较忙，嗯嗯，就是这里设置，这个是其他返回的推流地址，new StreamingProfile.Stream(mJSONObject); mJSONObject必须是七牛返回的内容，七牛地址是封装为json格式的
