### ISSUE TITLE
  大神   请问七牛的推流地址怎么设置？

### ISSUE THREAD

**Issue by backups123** [jjdxmashl/jjdxm_pililive#2]
大神           try {
                            UIUtils.showToastCenterShort("直播开始！");
                            mJSONObject = new JSONObject(liveId);
                            StreamingProfile.Stream stream = new StreamingProfile.Stream(mJSONObject);
                            mProfile.setStream(stream);  // You can invoke this before startStreaming, but not in initialization phase.
                            mCameraStreamingManager.setStreamingProfile(mProfile);
                            //这里没有打开只是简单测试功能没有去推流的
                            mCameraStreamingManager.startStreaming();
                            isStarted = true;
                        } catch (JSONException e) {
                            e.printStackTrace();
                            UIUtils.showToastCenterShort("推流地址解析失败！");
                        }

在这里如何设置？？？

**Comment by jjdxmashl** [comment]
@backups123 七牛推流地址是封装到json对象中的，你可以查看七牛的官方文档，或者让你们对接的后台兄弟提供接口返回

**Comment by JcmeLs** [comment]
可以直接设置URL不用封装JSON，setPublishUrl(publishurl)

**Comment by jjdxmashl** [comment]
@JcmeLs 可以吗？是七牛的sdk，不是ucloud的哦，可能有吧，不过我没有找到可以设置setPublishUrl的方法

**Comment by JcmeLs** [comment]
@jjdxmashl 可以的，不过我用的推流SDK版本是2.1.1，你的版本旧了不行，更新后变动有点大，所以对demo改动还是传stream流吧，如果自己重写的话用新版SDK就可以直接setPublishUrl(publishurl)
